# shadowsocks_ws.py — Shadowsocks TLS/WebSocket inbound for OXNET
import asyncio
import secrets
from datetime import datetime

from fastapi import WebSocket, WebSocketDisconnect

from main import (
    LINKS,
    LINKS_LOCK,
    stats,
    connections,
    error_logs,
    logger,
    is_link_allowed,
    save_state,
    log_activity,
    resolve_link_id,
)
from relay_vless import check_and_use, relay_ws_to_tcp, relay_tcp_to_ws


def _ws_client_ip(ws: WebSocket) -> str:
    fwd = ws.headers.get("x-forwarded-for")
    if fwd:
        return fwd.split(",")[0].strip()
    real_ip = ws.headers.get("x-real-ip")
    if real_ip:
        return real_ip.strip()
    return ws.client.host if ws.client else "نامشخص"


def parse_ss_none_header(chunk: bytes):
    """Parse Shadowsocks stream address header after client-side plugin/TLS transport.
    This inbound is for cipher=none links generated by OXNET.
    """
    if len(chunk) < 7:
        raise ValueError("chunk too small for ss header")
    pos = 0
    atyp = chunk[pos]; pos += 1
    if atyp == 1:
        if len(chunk) < pos + 4 + 2:
            raise ValueError("short ipv4 header")
        address = ".".join(str(b) for b in chunk[pos:pos+4]); pos += 4
    elif atyp == 3:
        if len(chunk) < pos + 1:
            raise ValueError("short domain header")
        ln = chunk[pos]; pos += 1
        if len(chunk) < pos + ln + 2:
            raise ValueError("short domain payload")
        address = chunk[pos:pos+ln].decode("utf-8", errors="ignore"); pos += ln
    elif atyp == 4:
        if len(chunk) < pos + 16 + 2:
            raise ValueError("short ipv6 header")
        ab = chunk[pos:pos+16]; pos += 16
        address = ":".join(f"{ab[i]:02x}{ab[i+1]:02x}" for i in range(0, 16, 2))
    else:
        raise ValueError(f"unknown ss atyp: {atyp}")
    port = int.from_bytes(chunk[pos:pos+2], "big"); pos += 2
    return address, port, chunk[pos:]


async def shadowsocks_ws_tunnel(ws: WebSocket, uuid: str):
    await ws.accept()
    uid = await resolve_link_id(uuid)
    async with LINKS_LOCK:
        link = LINKS.get(uid) if uid else None
    if not is_link_allowed(link):
        await ws.close(code=1008, reason="not authorized")
        return

    ip = _ws_client_ip(ws)
    conn_id = secrets.token_urlsafe(6)
    connections[conn_id] = {
        "uuid": uid,
        "ip": ip,
        "transport": "shadowsocks-tls",
        "connected_at": datetime.now().isoformat(),
        "bytes": 0,
    }
    writer = None
    try:
        first_msg = await asyncio.wait_for(ws.receive(), timeout=15.0)
        if first_msg["type"] == "websocket.disconnect":
            return
        first_chunk = first_msg.get("bytes") or (first_msg.get("text") or "").encode()
        if not first_chunk:
            return
        if not await check_and_use(uid, len(first_chunk)):
            await ws.close(code=1008, reason="quota/disabled")
            return
        address, port, payload = parse_ss_none_header(first_chunk)
        stats["total_requests"] += 1
        connections[conn_id]["bytes"] += len(first_chunk)
        reader, writer = await asyncio.wait_for(asyncio.open_connection(address, port), timeout=10.0)
        sock = writer.transport.get_extra_info('socket')
        if sock:
            import socket
            sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        if payload:
            writer.write(payload)
            await writer.drain()
        done, pending = await asyncio.wait({
            asyncio.create_task(relay_ws_to_tcp(ws, writer, conn_id, uid)),
            asyncio.create_task(relay_tcp_to_ws(ws, reader, conn_id, uid, vless_prefix=False)),
        }, return_when=asyncio.FIRST_COMPLETED)
        for t in pending:
            t.cancel()
            try:
                await t
            except asyncio.CancelledError:
                pass
        asyncio.create_task(save_state())
    except WebSocketDisconnect:
        pass
    except Exception as exc:
        stats["total_errors"] += 1
        error_logs.append({"error": f"ss-tls: {exc}", "time": datetime.now().isoformat()})
        logger.error(f"SS-TLS error [{conn_id}]: {exc}")
    finally:
        if writer:
            try:
                writer.close()
                await writer.wait_closed()
            except Exception:
                pass
        connections.pop(conn_id, None)
